apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: otel-collector
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: otel-collector
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/solace_msg_net: "true"
        io.kompose.service: otel-collector
    spec:
      containers:
        - args:
            - --config=/etc/otel-collector-config.yaml
            - ""
          image: otel/opentelemetry-collector-contrib:0.86.0
          name: otel-collector
          ports:
            - containerPort: 1888
            - containerPort: 8888
            - containerPort: 8889
            - containerPort: 13133
            - containerPort: 4317
            - containerPort: 55679
          resources: {}
          volumeMounts:
            - mountPath: /etc/otel-collector-config.yaml
              name: otel-collector-claim0
      hostname: otelcollector
      restartPolicy: Always
      volumes:
        - name: otel-collector-claim0
          hostPath:
            path: ../otel-collector-config.yaml
status: {}
