processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
    spike_limit_mib: 500

  batch:

exporters:
  logging:
    loglevel: "info"

  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

receivers:
  otlp:
    protocols:
      grpc:

  solace:
    broker: [solbroker:5672]
    max_unacknowledged: 500
    auth:
      sasl_plain:
        username: trace
        password: trace
    queue: queue://#telemetry-trace
    tls:
      insecure: true
      insecure_skip_verify: true


service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [solace, otlp]
      processors: [batch, memory_limiter]
      exporters: [jaeger, logging]
