version: "3"

services:
  rideshare-go-ap-south:
    ports:
      - 5000
    hostname: rideshare-go-ap-south
    environment: &env
      PYROSCOPE_SERVER_ADDRESS: http://pyroscope:4040
      OTLP_URL: tempo:4318
      OTLP_INSECURE: 1
      DEBUG_LOGGER: 1
      REGION: ap-south
    build:
      context: ../../golang-push/rideshare

  load-generator:
    environment: *env
    build:
      context: ../../golang-push/rideshare
      dockerfile: Dockerfile.load-generator
    command:
      - ./loadgen
      - rideshare-go-ap-south

  grafana:
    image: grafana/grafana-dev:10.3.0-151740
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_INSTALL_PLUGINS=pyroscope-panel
      - GF_FEATURE_TOGGLES_ENABLE=traceToProfiles tracesEmbeddedFlameGraph
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - '3000:3000'

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yml
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin

  pyroscope:
    image: grafana/pyroscope:1.3.0 
    environment:
      JAEGER_AGENT_HOST: tempo
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    ports:
      - '4040:4040'
    volumes:
      - ./pyroscope/pyroscope.yml:/etc/pyroscope.yml
    command:
      - 'server'
      - '-config.file=/etc/pyroscope.yml'
