{{- $tsdb := index .Values "timescaledb-single" -}}
{{ if $tsdb.enabled -}}
{{- /*
FIXME(paulfantom): Remove this ConfigMap when timescaleDB images start to be published with toolkit pre-enabled
*/}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-init-scripts
  namespace: {{ template "tobs.namespace" . }}
  labels:
   app: {{ template "tobs.fullname" . }}
   chart: {{ template "tobs.chart" . }}
   release: {{ .Release.Name }}
data:
  extensions.sql: |
    create extension if not exists timescaledb_toolkit;
    create extension if not exists pg_stat_statements;
    create extension if not exists pg_stat_monitor;
    create extension if not exists pg_stat_kcache;
    create extension if not exists pageinspect;
    create extension if not exists pg_buffercache;
    create extension if not exists pg_freespacemap;
{{- end -}}
